# Appointment - Preparazione Dataset

## Import delle librerie

Per prima cosa procediamo con l'importare tutte le librerie utili per la creazione dei dataset di train, validation e test.

In [1]:
!pip install --user -r requirements.txt

Requirement already satisfied: matplotlib==3.1.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from -r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: numpy==1.17.2 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from -r requirements.txt (line 2)) (1.17.2)
Requirement already satisfied: pandas==1.0.5 in c:\users\ricca\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 3)) (1.0.5)
Requirement already satisfied: scikit-learn==0.23.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from -r requirements.txt (line 4)) (0.23.1)
Requirement already satisfied: seaborn==0.10.1 in c:\users\ricca\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 5)) (0.10.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from matplotlib==3.1.1->-r requirements.txt (line 1)) (2.8.0)
Requirement already satisfied: cycler>=0.10 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from matplotlib==3.1.1->-r requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from matplotlib==3.1.1->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from matplotlib==3.1.1->-r requirements.txt (line 1)) (2.4.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\ricca\appdata\roaming\python\python37\site-packages (from pandas==1.0.5->-r requirements.txt (line 3)) (2020.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from scikit-learn==0.23.1->-r requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from scikit-learn==0.23.1->-r requirements.txt (line 4)) (1.4.1)
Requirement already satisfied: joblib>=0.11 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from scikit-learn==0.23.1->-r requirements.txt (line 4)) (0.15.1)
Requirement already satisfied: six>=1.5 in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from python-dateutil>=2.1->matplotlib==3.1.1->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: setuptools in c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages (from kiwisolver>=1.0.1->matplotlib==3.1.1->-r requirements.txt (line 1)) (41.4.0)

In [2]:
import pandas as pd
import sklearn as sl
import numpy as np

from sklearn.model_selection import train_test_split

## Caricamento del dataset completo

Caricamento del dataset appointment_data.csv.

In [3]:
url = 'appointment_data.csv'

app_data = pd.read_csv(url, na_values=np.nan)

In [4]:
app_data.head(15)

,No-show,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received
0,No,1.328492e+12,5687610,F,2016-05-11T16:00:16Z,2016-05-19T00:00:00Z,25,MATA DA PRAIA,0,0,0,0,0,0
1,No,3.881869e+14,5694484,M,2016-05-13T08:41:27Z,2016-05-17T00:00:00Z,62,FRADINHOS,0,0,0,0,0,0
2,Yes,9.118992e+12,5500939,F,2016-03-22T11:09:38Z,2016-05-09T00:00:00Z,65,JARDIM CAMBURI,0,0,0,0,0,0
3,No,1.843618e+14,5639080,M,2016-04-29T08:42:15Z,2016-04-29T00:00:00Z,41,MARIA ORTIZ,0,0,0,0,0,0
4,No,5.783198e+13,5671566,M,2016-05-06T18:47:52Z,2016-05-09T00:00:00Z,61,MARUÍPE,0,1,0,1,0,0
5,No,6.516246e+13,5600056,F,2016-04-19T09:52:22Z,2016-05-16T00:00:00Z,11,DO QUADRO,1,0,0,0,0,0
6,No,6.559800e+12,5640931,M,2016-04-29T11:44:39Z,2016-05-04T00:00:00Z,45,CRUZAMENTO,0,0,0,0,0,1
7,No,1.432925e+12,5730450,M,2016-05-24T08:37:44Z,2016-06-07T00:00:00Z,9,MÁRIO CYPRESTE,0,0,0,0,0,1
8,No,9.741488e+14,5771325,M,2016-06-03T12:24:24Z,2016-06-03T00:00:00Z,79,SOLON BORGES,0,0,0,0,0,0
9,No,5.458152e+12,5671279,M,2016-05-06T16:09:35Z,2016-05-10T00:00:00Z,60,TABUAZEIRO,0,1,0,0,0,1
10,No,3.271558e+11,5770308,F,2016-06-03T10:03:57Z,2016-06-03T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,0
11,No,1.397612e+12,5645083,M,2016-05-02T09:28:05Z,2016-05-02T00:00:00Z,13,SANTA LUÍZA,0,0,0,0,0,0
12,No,6.195160e+13,5682576,F,2016-05-10T17:21:16Z,2016-06-07T00:00:00Z,19,JABOUR,0,0,0,0,0,1
13,Yes,7.263648e+13,5397258,M,2016-02-25T14:30:51Z,2016-04-29T00:00:00Z,52,RESISTÊNCIA,0,0,1,0,0,0
14,No,1.863334e+12,5660484,F,2016-05-04T16:42:20Z,2016-05-06T00:00:00Z,53,FORTE SÃO JOÃO,0,0,0,0,0,0

## Split del dataset

Dividiamo il dataset in tre parti: Train, Validation e Test

In [5]:
# Dividiamo il dataset in tre parti: Train,
# Validation e Test.
train, test = train_test_split(app_data, test_size=.2)
train, validation = train_test_split(train, test_size=.2)

Saviamo i dataset appena creati in file csv

In [6]:
train.to_csv('train.csv', index=False)
validation.to_csv('validation.csv', index=False)
test.to_csv('test.csv', index=False)

## Split del dataset

Dividiamo il dataset in tre parti: Train, Validation e Test

In [7]:
# Dividiamo il dataset in tre parti: Train,
# Validation e Test.
train, test = train_test_split(app_data, test_size=.2)
train, validation = train_test_split(train, test_size=.2)

Saviamo i dataset appena creati in file csv

In [8]:
train.to_csv('train.csv', index=False)
validation.to_csv('validation.csv', index=False)
test.to_csv('test.csv', index=False)